---
name: NQP - Checks

on:
  pull_request:
    types: [opened, edited, synchronize]
  push:
    branches:
      - '!develop'
      - '!master'
      - pypy


jobs:
  build:
    name: Checks
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.8, pypy37]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        if: ${{ matrix.python-version == '3.8' }}
        with:
          python-version: ${{ matrix.python-version }}

      - if: ${{ matrix.python-version == 'pypy37' && matrix.os == 'windows-latest' }}
        run: |
          cd vendor/
          curl -L -O https://downloads.python.org/pypy/pypy3.7-v7.3.2-win32.zip
          unzip pypy3.7-v7.3.2-win32.zip
          cd pypy3.7-v7.3.2-win32/
          echo ${{ env.working-directory }} >> $GITHUB_PATH
          ln -s ${{ env.working-directory }}/pypy3.exe ${{ env.working-directory }}/python
          pypy3.exe -m pip install --upgrade pip virtualenv
          pypy3.exe -m virtualenv ../civenv/
          call ../civenv/Scripts/activate.bat

      - name: Locate Pip Cache
        id: pip-cache
        run: echo "::set-output name=dir::$(python -m pip cache dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/poetry.lock') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install Linux dependencies
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt-get update
          sudo apt-get install libsdl2-dev
          sudo apt-get install python-sphinx

      - name: Install dependencies
        run: |
          python -V
          python -m pip install --upgrade poetry
          poetry config virtualenvs.create false
          poetry install --no-root -E docs

      - name: Check code formatting
        run: |
          poetry run black --check scripts/

      - name: mypy Type Check
        if: ${{ matrix.python-version == '3.8' }}
        run: |
          poetry run mypy scripts/

      - name: Pytest with Coverage
        run: |
          poetry run pytest --cov=nqp

      - name: Check Docs Build
        run: |
          sphinx-apidoc -o ./docs .
          cd docs
          sphinx-build -a -E --keep-going . _build
